
server:
  port: 9007

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 377825014181-2tpha7niq0hjar86e4j8h6dl0h8j1s3i.apps.googleusercontent.com
            client-secret: yyHXhXWBRrx3jyDWrhiSwzu8
          facebook:
            client-id: 488695445381590
            client-secret: bcbbc8a3a1d98bedeb258b318878e745
          kakao:
            client-id: fa84d469d8038b6a422d1f9b2b6f9067
            client-secert: RuubX7J4HuhrekWplEeu2FnlSMiCftHH
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-name: kakao
          naver:
            client-id: bkdZjYp4EfmqIkZaEtqi
            client-secret: YLHoiLkdSy
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-name: naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  data:
    mongodb:
      database: oauth2-client-test
      host: localhost
      port: 27018